VERZIJA=CDX
MODUL=fin_1dok


SRCDOSROOT=$(BASEDOS)\\fmk\\fin\\dok\\1g\\

PRGS=knjiz.prg knjiz2.prg povrat.prg stdatn.prg stonal.prg mnu_oop.prg mnu_preg.prg oasist.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
