VERZIJA=CDX
MODUL=fin_1dok

SRCDOSROOT=c:\\dev\\fmk\\fin\\dok\\1g\\

PRGS=knjiz.prg knjiz2.prg povrat.prg stdatn.prg stonal.prg mnu_oop.prg mnu_preg.prg oasist.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
