VERZIJA=CDX
MODUL=fin_1rpt

SRCDOSROOT=c:\\dev\\fmk\\fin\\rpt\\1g\\

PRGS=bilans.prg kartas.prg kartica.prg mnu_rpt.prg ostalo.prg proizv.prg specif.prg mnu_spec.prg rpt_dug.prg blag_di.prg spec_ut.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
