VERZIJA=CDX
MODUL=fin_1rpt


SRCDOSROOT=$(BASEDOS)\\fmk\\fin\\rpt\\1g\\

PRGS=bilans.prg kartas.prg kartica.prg mnu_rpt.prg ostalo.prg proizv.prg specif.prg mnu_spec.prg rpt_dug.prg blag_di.prg spec_ut.prg lst_nal.prg spec_tr.prg spec_an.prg

CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
