VERZIJA=CDX
MODUL=fin_1rdb


SRCDOSROOT=$(BASEDOS)\\fmk\\fin\\razdb\\1g\\


PRGS=ldfin.prg faktfin.prg mnu_raz.prg pos_fin.prg blag_fin.prg elba.prg
CS=
ASMS=

include ../../../fmk_lib/Makefile_clipper
