VERZIJA=CDX
MODUL=fin_1rdb

SRCDOSROOT=c:\\dev\\fmk\\fin\\razdb\\1g\\

PRGS=ldfin.prg faktfin.prg mnu_raz.prg pos_fin.prg blag_fin.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
