VERZIJA=CDX
MODUL=fin_2db

SRCDOSROOT=c:\\dev\\fmk\\fin\\db\\2g\\

PRGS=db.prg mnu_adm.prg

CS=
ASMS=
OBJS=$(OBJPRGS) $(OBJCS) $(OBJASMS)

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper
